# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\"_\n\x10TranslateRequest\x12\x19\n\x11text_to_translate\x18\x01 \x01(\t\x12\x17\n\x0fsource_language\x18\x02 \x01(\t\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\",\n\x11TranslateResponse\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t2I\n\x11TranslatorService\x12\x34\n\tTranslate\x12\x11.TranslateRequest\x1a\x12.TranslateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATEREQUEST']._serialized_start=23
  _globals['_TRANSLATEREQUEST']._serialized_end=118
  _globals['_TRANSLATERESPONSE']._serialized_start=120
  _globals['_TRANSLATERESPONSE']._serialized_end=164
  _globals['_TRANSLATORSERVICE']._serialized_start=166
  _globals['_TRANSLATORSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
