# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import model_service_pb2 as proto_dot_model__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/model_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslatorServiceStub(object):
    """我們可以將服務名稱改得更貼切，例如 TranslatorService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.unary_unary(
                '/model.v1.TranslatorService/Translate',
                request_serializer=proto_dot_model__service__pb2.TranslateRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.TranslateResponse.FromString,
                _registered_method=True)


class TranslatorServiceServicer(object):
    """我們可以將服務名稱改得更貼切，例如 TranslatorService
    """

    def Translate(self, request, context):
        """定義一個名為 Translate 的 RPC (遠端程序呼叫)
        它接收 TranslateRequest，並回傳 TranslateResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=proto_dot_model__service__pb2.TranslateRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.TranslateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.v1.TranslatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model.v1.TranslatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslatorService(object):
    """我們可以將服務名稱改得更貼切，例如 TranslatorService
    """

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.TranslatorService/Translate',
            proto_dot_model__service__pb2.TranslateRequest.SerializeToString,
            proto_dot_model__service__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MediaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Wav2Lip = channel.unary_unary(
                '/model.v1.MediaService/Wav2Lip',
                request_serializer=proto_dot_model__service__pb2.Wav2LipRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.Wav2LipResponse.FromString,
                _registered_method=True)
        self.Tts = channel.unary_unary(
                '/model.v1.MediaService/Tts',
                request_serializer=proto_dot_model__service__pb2.TtsRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.TtsResponse.FromString,
                _registered_method=True)
        self.SpeakerAnnote = channel.unary_unary(
                '/model.v1.MediaService/SpeakerAnnote',
                request_serializer=proto_dot_model__service__pb2.SpeakerAnnoteRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.SpeakerAnnoteResponse.FromString,
                _registered_method=True)
        self.SpeechRecognition = channel.unary_unary(
                '/model.v1.MediaService/SpeechRecognition',
                request_serializer=proto_dot_model__service__pb2.SpeechRecognitionRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.SpeechRecognitionResponse.FromString,
                _registered_method=True)
        self.GenerateText = channel.unary_unary(
                '/model.v1.MediaService/GenerateText',
                request_serializer=proto_dot_model__service__pb2.TextGenerationRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.TextGenerationResponse.FromString,
                _registered_method=True)
        self.ChatCompletion = channel.unary_unary(
                '/model.v1.MediaService/ChatCompletion',
                request_serializer=proto_dot_model__service__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)
        self.AnswerQuestionFromDocuments = channel.unary_unary(
                '/model.v1.MediaService/AnswerQuestionFromDocuments',
                request_serializer=proto_dot_model__service__pb2.AnswerQuestionRequest.SerializeToString,
                response_deserializer=proto_dot_model__service__pb2.AnswerQuestionResponse.FromString,
                _registered_method=True)


class MediaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Wav2Lip(self, request, context):
        """1. Wav2Lip: 根據音訊和圖片產生對嘴影片
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tts(self, request, context):
        """2. TTS (Text-to-Speech): 將文字轉換為語音
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeakerAnnote(self, request, context):
        """3. SpeakerAnnote (Speaker Annotation/Diarization): 說話者日誌
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeechRecognition(self, request, context):
        """4. SpeechRecognition (Speech-to-Text): 語音識別
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateText(self, request, context):
        """LLM 服務
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnswerQuestionFromDocuments(self, request, context):
        """新增的 RAG 問答 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Wav2Lip': grpc.unary_unary_rpc_method_handler(
                    servicer.Wav2Lip,
                    request_deserializer=proto_dot_model__service__pb2.Wav2LipRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.Wav2LipResponse.SerializeToString,
            ),
            'Tts': grpc.unary_unary_rpc_method_handler(
                    servicer.Tts,
                    request_deserializer=proto_dot_model__service__pb2.TtsRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.TtsResponse.SerializeToString,
            ),
            'SpeakerAnnote': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeakerAnnote,
                    request_deserializer=proto_dot_model__service__pb2.SpeakerAnnoteRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.SpeakerAnnoteResponse.SerializeToString,
            ),
            'SpeechRecognition': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechRecognition,
                    request_deserializer=proto_dot_model__service__pb2.SpeechRecognitionRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.SpeechRecognitionResponse.SerializeToString,
            ),
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=proto_dot_model__service__pb2.TextGenerationRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.TextGenerationResponse.SerializeToString,
            ),
            'ChatCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=proto_dot_model__service__pb2.ChatCompletionRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.ChatCompletionResponse.SerializeToString,
            ),
            'AnswerQuestionFromDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.AnswerQuestionFromDocuments,
                    request_deserializer=proto_dot_model__service__pb2.AnswerQuestionRequest.FromString,
                    response_serializer=proto_dot_model__service__pb2.AnswerQuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.v1.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model.v1.MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Wav2Lip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.MediaService/Wav2Lip',
            proto_dot_model__service__pb2.Wav2LipRequest.SerializeToString,
            proto_dot_model__service__pb2.Wav2LipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.MediaService/Tts',
            proto_dot_model__service__pb2.TtsRequest.SerializeToString,
            proto_dot_model__service__pb2.TtsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeakerAnnote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.MediaService/SpeakerAnnote',
            proto_dot_model__service__pb2.SpeakerAnnoteRequest.SerializeToString,
            proto_dot_model__service__pb2.SpeakerAnnoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeechRecognition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.MediaService/SpeechRecognition',
            proto_dot_model__service__pb2.SpeechRecognitionRequest.SerializeToString,
            proto_dot_model__service__pb2.SpeechRecognitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.MediaService/GenerateText',
            proto_dot_model__service__pb2.TextGenerationRequest.SerializeToString,
            proto_dot_model__service__pb2.TextGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.MediaService/ChatCompletion',
            proto_dot_model__service__pb2.ChatCompletionRequest.SerializeToString,
            proto_dot_model__service__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnswerQuestionFromDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.v1.MediaService/AnswerQuestionFromDocuments',
            proto_dot_model__service__pb2.AnswerQuestionRequest.SerializeToString,
            proto_dot_model__service__pb2.AnswerQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
