# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\x12\x08model.v1\"_\n\x10TranslateRequest\x12\x19\n\x11text_to_translate\x18\x01 \x01(\t\x12\x17\n\x0fsource_language\x18\x02 \x01(\t\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\",\n\x11TranslateResponse\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t\"8\n\x0eWav2LipRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"%\n\x0fWav2LipResponse\x12\x12\n\nvideo_data\x18\x01 \x01(\x0c\"<\n\nTtsRequest\x12\x15\n\rtext_to_speak\x18\x01 \x01(\t\x12\x17\n\x0freference_audio\x18\x02 \x01(\x0c\"&\n\x0bTtsResponse\x12\x17\n\x0fgenerated_audio\x18\x01 \x01(\x0c\"*\n\x14SpeakerAnnoteRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"K\n\x12\x44iarizationSegment\x12\x0f\n\x07speaker\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x01\"R\n\x0fSpeakerTimeline\x12\x0f\n\x07speaker\x18\x01 \x01(\t\x12.\n\x08segments\x18\x02 \x03(\x0b\x32\x1c.model.v1.DiarizationSegment\"\x81\x01\n\x15SpeakerAnnoteResponse\x12\x32\n\x0c\x61ll_segments\x18\x01 \x03(\x0b\x32\x1c.model.v1.DiarizationSegment\x12\x34\n\x11speaker_timelines\x18\x02 \x03(\x0b\x32\x19.model.v1.SpeakerTimeline2[\n\x11TranslatorService\x12\x46\n\tTranslate\x12\x1a.model.v1.TranslateRequest\x1a\x1b.model.v1.TranslateResponse\"\x00\x32\xda\x01\n\x0cMediaService\x12@\n\x07Wav2Lip\x12\x18.model.v1.Wav2LipRequest\x1a\x19.model.v1.Wav2LipResponse\"\x00\x12\x34\n\x03Tts\x12\x14.model.v1.TtsRequest\x1a\x15.model.v1.TtsResponse\"\x00\x12R\n\rSpeakerAnnote\x12\x1e.model.v1.SpeakerAnnoteRequest\x1a\x1f.model.v1.SpeakerAnnoteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATEREQUEST']._serialized_start=33
  _globals['_TRANSLATEREQUEST']._serialized_end=128
  _globals['_TRANSLATERESPONSE']._serialized_start=130
  _globals['_TRANSLATERESPONSE']._serialized_end=174
  _globals['_WAV2LIPREQUEST']._serialized_start=176
  _globals['_WAV2LIPREQUEST']._serialized_end=232
  _globals['_WAV2LIPRESPONSE']._serialized_start=234
  _globals['_WAV2LIPRESPONSE']._serialized_end=271
  _globals['_TTSREQUEST']._serialized_start=273
  _globals['_TTSREQUEST']._serialized_end=333
  _globals['_TTSRESPONSE']._serialized_start=335
  _globals['_TTSRESPONSE']._serialized_end=373
  _globals['_SPEAKERANNOTEREQUEST']._serialized_start=375
  _globals['_SPEAKERANNOTEREQUEST']._serialized_end=417
  _globals['_DIARIZATIONSEGMENT']._serialized_start=419
  _globals['_DIARIZATIONSEGMENT']._serialized_end=494
  _globals['_SPEAKERTIMELINE']._serialized_start=496
  _globals['_SPEAKERTIMELINE']._serialized_end=578
  _globals['_SPEAKERANNOTERESPONSE']._serialized_start=581
  _globals['_SPEAKERANNOTERESPONSE']._serialized_end=710
  _globals['_TRANSLATORSERVICE']._serialized_start=712
  _globals['_TRANSLATORSERVICE']._serialized_end=803
  _globals['_MEDIASERVICE']._serialized_start=806
  _globals['_MEDIASERVICE']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
